//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

public class NPCActionFactory
{


	static public GameObject get_npc_action(NPCActionMGR.NPCActionTypes action){
		GameObject actionGo = new GameObject();

		switch(action){
		case NPCActionMGR.NPCActionTypes.MOVE_FORWARD:
			actionGo.AddComponent("NPC_MoveForward");
			actionGo.name = "Move Forward";
			break;
		case NPCActionMGR.NPCActionTypes.STOP_MOVING:
			break;

		}
		return actionGo;
	}


}


